#!/bin/bash
#You can also perform this action in beforehand using 'kubeadm config images pull'
# The addition of --cri-socket=/var/run/crio/crio.sock was added to accomodate the container runtime element.

sudo kubeadm --apiserver-advertise-address=10.0.0.17 --cri-socket=/var/run/crio/crio.sock init
##  Flannel only ##


# kubeadm --apiserver-advertise-address=10.0.0.17:8080 --pod-network-cidr 10.244.0.0/16 init 
